
language: android

branches:
  only:
    - main

script: "./gradlew clean assembleRelease"

android:
  components:
      - platform-tools
      - tools
      - build-tools-24.0.2
      - android-24
      - extra-android-m2repository
      
